spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springcloud
    username: admin
    password: admin
  redis:
    host: localhost
    port: 6379

  flyway:
    url: jdbc:postgresql://localhost:5432/springcloud
    user: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate