CREATE USER SKYCLOUD IDENTIFIED BY "root"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;
ALTER USER "SKYCLOUD" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO SKYCLOUD;

CREATE SEQUENCE  "SKYCLOUD"."CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "SKYCLOUD"."CLIENT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LOGIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "CLIENT_UK1" UNIQUE ("LOGIN"));

  CREATE OR REPLACE TRIGGER "SKYCLOUD"."BI_CLIENT" 
  before insert on "SKYCLOUD"."CLIENT"
for each row  
begin   
  if :NEW."ID" is null then 
    select "CLIENT_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "SKYCLOUD"."BI_CLIENT" ENABLE;


CREATE SEQUENCE  "SKYCLOUD"."USERFILE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

  CREATE TABLE "SKYCLOUD"."USERFILE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PATH" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USERFILE_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "USERFILE_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SKYCLOUD"."CLIENT" ("ID") ENABLE
   );

  CREATE OR REPLACE TRIGGER "SKYCLOUD"."BI_USERFILE" 
  before insert on "SKYCLOUD"."USERFILE"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "USERFILE_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER "SKYCLOUD"."BI_USERFILE" ENABLE;