INVALID_USER_MESSAGE = Invalid login or password
SERVER_PROBLEM_MESSAGE = Sorry, but we have some problems. Try again later
USER_EXISTS_MESSAGE = This user already exists
DELETING_FAILED_MESSAGE = Can't delete this file. Try again later
SAVING_FAILED_MESSAGE = Can't save this file. Try again later
RENAME_FAILED_MESSAGE = Can't rename this file. Try again later
FILE_EXISTS_MESSAGE = This file already exists. Delete This file and try again
NULL_FIELD_MESSAGE = Attribute can't be empty
INVALID_LOGIN_SIZE = Login must be 3-20 chars
INVALID_PASSWORD_SIZE = Password must be 3-20 chars
EMPTY_LOGIN = Empty login
EMPTY_PASSWORD = Empty password
EMPTY_FILE_ID = Empty file id
EMPTY_FILE_NAME = Empty file name
INVALID_FILE_NAME_SIZE = File name must be 1-250 chars
EMPTY_FILE_CONTENT = Empty file content
INVALID_FILE_NAME = Wrong symbols \\, /, :, *, ?, |