version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=springcloud
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    volumes:
      - ./redis-data:/redis-data
    stdin_open: true
    tty: true
    ports:
      - '6379:6379'